/**
 * reportSchedulerService.js
 *
 * Loads all active ScheduledReport documents from MongoDB on server start,
 * registers a node-cron task for each one, and writes a Report history entry
 * every time a scheduled report fires.
 *
 * Exported functions:
 *  - initScheduler()          : Call once in server.js after DB connects.
 *  - scheduleOne(doc)         : Register a single cron task for a ScheduledReport doc.
 *  - unscheduleOne(id)        : Stop and remove a running cron task.
 *  - rescheduleAll()          : Reload all schedules from DB (e.g. after create/update).
 */

const cron = require('node-cron');
const mongoose = require('mongoose');

// Lazy-require models to avoid circular-dependency issues at boot
const getScheduledReport = () => require('../models/ScheduledReport');
const getReport = () => require('../models/Report');

// Map of scheduleId (string) → node-cron task instance
const activeTasks = new Map();

// ─────────────────────────────────────────────────────────────
// Internal: run one scheduled report and log to history
// ─────────────────────────────────────────────────────────────
async function runScheduledReport(doc) {
    try {
        const Report = getReport();
        const ScheduledReport = getScheduledReport();

        console.log(`[Scheduler] Running: "${doc.title}" (${doc.type}) at ${new Date().toISOString()}`);

        // Write history entry
        await Report.create({
            title: `[AUTOMATED] ${doc.title} (Scheduled)`,
            action: `${doc.type} report auto-generated by schedule`,
            type: doc.type,
            format: 'Scheduled',
            filters: {},
            generatedAt: new Date(),
        });

        // Update lastRun on the schedule document
        await ScheduledReport.findByIdAndUpdate(doc._id, { lastRun: new Date() });

        console.log(`[Scheduler] ✅ Completed: "${doc.title}"`);
    } catch (err) {
        console.error(`[Scheduler] ❌ Error running "${doc.title}":`, err.message);
    }
}

// ─────────────────────────────────────────────────────────────
// Register a cron task for one ScheduledReport document
// ─────────────────────────────────────────────────────────────
function scheduleOne(doc) {
    const id = String(doc._id);

    // Stop existing task if it exists
    unscheduleOne(id);

    if (!doc.active) {
        console.log(`[Scheduler] Skipping inactive schedule: "${doc.title}"`);
        return;
    }

    const expression = doc.cronExpression || '0 8 * * *';

    if (!cron.validate(expression)) {
        console.warn(`[Scheduler] Invalid cron expression "${expression}" for "${doc.title}". Skipping.`);
        return;
    }

    const task = cron.schedule(expression, () => runScheduledReport(doc), {
        timezone: 'Asia/Colombo', // UTC+5:30 — Sri Lanka
    });

    activeTasks.set(id, task);
    console.log(`[Scheduler] Registered: "${doc.title}" → ${expression}`);
}

// ─────────────────────────────────────────────────────────────
// Stop and remove a running cron task by schedule ID
// ─────────────────────────────────────────────────────────────
function unscheduleOne(id) {
    if (activeTasks.has(id)) {
        activeTasks.get(id).stop();
        activeTasks.delete(id);
        console.log(`[Scheduler] Unregistered task: ${id}`);
    }
}

// ─────────────────────────────────────────────────────────────
// Load all active schedules from DB and register cron tasks
// ─────────────────────────────────────────────────────────────
async function rescheduleAll() {
    // Stop all existing tasks first
    for (const [id, task] of activeTasks.entries()) {
        task.stop();
    }
    activeTasks.clear();

    if (mongoose.connection.readyState !== 1) {
        console.warn('[Scheduler] MongoDB not connected — skipping schedule load.');
        return;
    }

    try {
        const ScheduledReport = getScheduledReport();
        const schedules = await ScheduledReport.find({ active: true });
        schedules.forEach(scheduleOne);
        console.log(`[Scheduler] Loaded ${schedules.length} active schedule(s).`);
    } catch (err) {
        console.error('[Scheduler] Failed to load schedules:', err.message);
    }
}

// ─────────────────────────────────────────────────────────────
// Seed default schedules if the collection is empty
// ─────────────────────────────────────────────────────────────
async function seedDefaultSchedules() {
    try {
        const ScheduledReport = getScheduledReport();
        const count = await ScheduledReport.countDocuments();
        if (count > 0) return;

        const defaults = [
            { title: 'Daily Sales Summary',       type: 'Sales',             frequency: 'Every day at 8:00 PM',      cronExpression: '0 20 * * *',  active: true },
            { title: 'Weekly Inventory Report',   type: 'Inventory',         frequency: 'Every Monday at 9:00 AM',   cronExpression: '0 9 * * 1',   active: true },
            { title: 'Monthly Branch Performance',type: 'Branch Performance',frequency: 'First day of every month',  cronExpression: '0 0 1 * *',   active: true },
            { title: 'Quarterly Business Summary',type: 'Business Summary',  frequency: 'Every 3 months',            cronExpression: '0 0 1 */3 *', active: false },
        ];

        await ScheduledReport.insertMany(defaults);
        console.log('[Scheduler] Seeded 4 default scheduled reports.');
    } catch (err) {
        console.error('[Scheduler] Seed error:', err.message);
    }
}

// ─────────────────────────────────────────────────────────────
// Main entry point — call after DB connection is established
// ─────────────────────────────────────────────────────────────
async function initScheduler() {
    console.log('[Scheduler] Initializing report scheduler...');
    await seedDefaultSchedules();
    await rescheduleAll();
}

module.exports = {
    initScheduler,
    scheduleOne,
    unscheduleOne,
    rescheduleAll,
};
